# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_valet',
            field=models.BooleanField(default=False),
        ),
    ]
