# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 02:51
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160413_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=accounts.models.upload_to),
        ),
    ]
