# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 04:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20160418_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredvehicle',
            name='owned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_vehicle', to=settings.AUTH_USER_MODEL),
        ),
    ]
