# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20160418_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
