# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 04:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_auto_20160418_1632'),
        ('accounts', '0008_user_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Location'),
        ),
    ]
