# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(blank=True, max_length=255, null=True, verbose_name='latitude')),
                ('lng', models.CharField(blank=True, max_length=255, null=True, verbose_name='longitude')),
                ('full_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='full address')),
            ],
            options={
                'db_table': 'gps_locations',
            },
        ),
    ]
