# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20160417_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intersectionlatlng',
            name='lat',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='intersectionlatlng',
            name='lng',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='longitude'),
        ),
    ]
