# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('orders', '0002_auto_20160414_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dropoff',
            name='valet_starting_location',
        ),
        migrations.RemoveField(
            model_name='repark',
            name='valet_starting_location',
        ),
        migrations.AddField(
            model_name='dropoff',
            name='valet_start_pos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_dropoff_related', to='locations.Location'),
        ),
        migrations.AddField(
            model_name='repark',
            name='valet_start_pos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_repark_related', to='locations.Location'),
        ),
    ]
