# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_scheduledrepark'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledrepark',
            name='is_scheduled_repark',
            field=models.BooleanField(default=True),
        ),
    ]
