# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_scheduledrepark_is_scheduled_repark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropoff',
            name='requested_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='repark',
            name='requested_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='scheduledrepark',
            name='requested_at',
            field=models.DateTimeField(),
        ),
    ]
