# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20160421_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropoff',
            name='request_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='repark',
            name='request_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='scheduledrepark',
            name='request_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
