# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-29 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20160421_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropoff',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='repark',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduledrepark',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
